name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camerakit_flutter: ^1.0.3
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.12.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.camerakit.camerakit_flutter
        pluginClass: CamerakitFlutterPlugin
      ios:
        pluginClass: CamerakitFlutterPlugin
      web:
        pluginClass: CamerakitFlutterWeb
        fileName: camerakit_flutter_web.dart